# Generated by Django 5.0 on 2024-02-16 06:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnsdadweb', '0003_appcredentials_app_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=250)),
                ('connection_time', models.DateField(default=datetime.date.today)),
                ('completion_time', models.DateField(default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('MANUAL', 'manual'), ('CLOSED', 'closed')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateField(default=datetime.date.today)),
                ('deleted', models.DateField(default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsdadweb.appcredentials')),
            ],
        ),
    ]
