# Generated by Django 5.0 on 2024-02-15 08:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('client_id', models.CharField(max_length=250, unique=True)),
                ('client_secret', models.CharField(max_length=250, unique=True)),
                ('redirect_uris', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateField(default=datetime.date.today)),
                ('deleted', models.DateField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppCredentialsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, unique=True)),
                ('expires', models.DateTimeField()),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateField(default=datetime.date.today)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsdadweb.appcredentials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
