# Generated by Django 5.0 on 2024-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsdadweb', '0002_alter_appcredentials_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredentials',
            name='app_image',
            field=models.ImageField(null=True, upload_to='app_images/'),
        ),
    ]
